services:
  mysql-spring-db:
    image: 'mysql:8.0'
    container_name: mysql-spring-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=my_project_db_ingenieria
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local