name: Backend Java Linting

on:
  push:
    branches: [ "main", "deibi" ]
    # Only trigger if files inside the backend folder change
    paths:
      - 'projectflow-backend/**' 
  pull_request:
    branches: [ "main" ]
    paths:
      - 'projectflow-backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    # This tells every 'run' step in this job to execute inside the backend directory
    defaults:
      run:
        working-directory: ./projectflow-backend

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    # Maven will now look for the pom.xml inside the ./backend folder
    - name: Run Checkstyle
      run: mvn checkstyle:check