name: Backend Build & Test

on:
  push:
    branches: [ "main", "deibi" ]
    paths:
      - 'projectflow-backend/**' 
  pull_request:
    branches: [ "main" ]
    paths:
      - 'projectflow-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./projectflow-backend

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    # 3. Compile, Lint, and Test the project
    # 'verify' runs compilation, checkstyle (because it's tied to the build lifecycle), and tests
    - name: Build and Test
      run: mvn clean verify