name: Frontend CI

on:
  push:
    branches: [ "main", "deibi", "daniel" ]
    paths:
      - 'projectflow-frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'projectflow-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.19.0'
        cache: 'npm'
        cache-dependency-path: projectflow-frontend/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: projectflow-frontend

    - name: Run linter
      run: npm run lint
      working-directory: projectflow-frontend

    - name: Build project
      run: npm run build
      working-directory: projectflow-frontend